function[] = fPlotMuhxFr(Xhx,Xbhx,xInterphx,Yhx,Ybhx,yInterphx, ...
                lyInterphx, lyInterpFr, uyInterphx, uyInterpFr, ...
                coeffshx07Fr05, ... 
                XFr,XbFr,xInterpFr,YFr,YbFr,yInterpFr, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 28;
MarkerS = 15;
yPos = 0.82; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
colors=zeros(size(colors));
colors(7,:)=[0 0 0];
limColor = [.65 .65 .65];
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
lStyles = {'none','none','none','-','-.','--'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/1.6]);



%% SUBPLOT a) -- hx
subplot1 = subplot(1,2,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',[0.0,0.2,0.4,0.6,0.8,1],...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:0.2:1,...
    'LineWidth', 1.5);
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 1]);
ylim(subplot1,[0. 1]);

% create plot of h* without bedload
plot1(1) = plot(Xhx(:,3),Yhx(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName','vertical a_*');
% create plot of b* without bedload
plot1(2) = plot(Xhx(:,2),Yhx(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName','lateral b_*');
% create plot of a*b* without bedload
plot1(3) = plot(Xhx(:,1),Yhx(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','combined a_* \cdot b_*');
lgnd = legend(subplot1,'show','Location','SouthWest');
% legend boxoff
% set(lgnd,'color','none');

% create plot of h* with bedload
plot1(4) = plot(Xbhx(:,3),Ybhx(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','top a_* (with bedload)');
% create plot of b* without bedload
plot1(5) = plot(Xbhx(:,2),Ybhx(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','lateral b_* (with bedload)');
% create plot of a*b* without bedload
plot1(6) = plot(Xbhx(:,1),Ybhx(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','combined a_* \cdot b_* (with bedload)');

% create plot of regression curve hx < 0.7
plot1(7) = plot(xInterphx,yInterphx,...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% lower bounds
plot1(8) = plot(xInterphx,lyInterphx,...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% upper bounds
plot1(9) = plot(xInterphx,uyInterphx,...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

% create plot of regression curve hx > 0.7
xhx07 = 0.7:0.1:1;
yhx07 = ones(size(xhx07));
plot1(10) = plot(xhx07,yhx07.*coeffshx07Fr05(2,3),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% % lower bounds
% plot1(11) = plot(xhx07,yhx07.*coeffshx07Fr05(1,3),...
%     'Color',limColor,...
%     'LineWidth',1,'LineStyle',lStyles{1,5},...
%     'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
%     'DisplayName','Regression curve');
% % upper bounds
% plot1(12) = plot(xhx07,yhx07.*coeffshx07Fr05(3,3),...
%     'Color',limColor,...
%     'LineWidth',1,'LineStyle',lStyles{1,5},...
%     'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
%     'DisplayName','Regression curve');

% create plot of threshold value hx = 0.7
plot1(13) = plot([0.7,0.7],[0,1],...
    'Color',[0.2,0.2,0.2],...
    'LineWidth',.5,'LineStyle',lStyles{1,6},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Threshold value h_*');

fMakeXgrid(0.2:0.2:0.8,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:0.8,0.5);

% Create xlabel
xlabel('Backwater ratio h_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Discharge coefficient \mu [-]',...
    'FontSize',fontS,...
    'FontName','Arial');
annotation(figure1,'textbox',...
        [0.14 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...        
        'LineStyle','none');
		
annotation(figure1,'textbox',...
        [0.3472 .0433333333  0.8 0.1],... % [x_begin y_begin length height]
        'String',{'0.7'},...
        'FontName','Arial','FontSize',fontS,...
        'Color',[0.35,0.35,0.35],...
        'FitBoxToText','on',...%'BackgroundColor',[1 1 1],...
        'LineStyle','none');

%% SUBPLOT b) -- Fr
subplot2 = subplot(1,2,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',[0.0,0.2,0.4,0.6,0.8,1],...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:0.2:1,...
    'LineWidth', 1.5);
hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0. 1]);
ylim(subplot2,[0. 1]);

% create plot of Fr without bedload
plot2(1) = plot(XFr(:,3),YFr(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName','vertical a_*');
% create plot of b* without bedload
plot2(2) = plot(XFr(:,2),YFr(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName','lateral b_*');
% create plot of a*b* without bedload
plot2(3) = plot(XFr(:,1),YFr(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','combined a_* \cdot b_*');
% legend(axes1,'show','Location','NorthWest');

% create plot of Fr with bedload
plot2(4) = plot(XbFr(:,3),YbFr(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','top a_* (with bedload)');
% create plot of b* without bedload
plot2(5) = plot(XbFr(:,2),YbFr(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','lateral b_* (with bedload)');
% create plot of a*b* without bedload
plot2(6) = plot(XbFr(:,1),YbFr(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','combined a_* \cdot b_* (with bedload)');

% create plot of regression curve Fr < 0.5
plot2(7) = plot(xInterpFr,yInterpFr,...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% lower bounds
plot2(8) = plot(xInterpFr,lyInterpFr,...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% upper bounds
plot2(9) = plot(xInterpFr,uyInterpFr,...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

% create plot of regression curve Fr > 0.5
xFr05 = 0.5:0.1:1;
yFr05 = ones(size(xFr05));
plot2(10) = plot(xFr05,yFr05.*coeffshx07Fr05(2,3),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% % lower bounds
% plot2(11) = plot(xFr05,yFr05.*coeffshx07Fr05(1,3),...
%     'Color',limColor,...
%     'LineWidth',1,'LineStyle',lStyles{1,5},...
%     'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
%     'DisplayName','Regression curve');
% % upper bounds
% plot2(12) = plot(xFr05,yFr05.*coeffshx07Fr05(3,3),...
%     'Color',limColor,...
%     'LineWidth',1,'LineStyle',lStyles{1,5},...
%     'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
%     'DisplayName','Regression curve');

% create plot of threshold value Fr = 0.5
plot2(13) = plot([0.5,0.5],[0,1],...
    'Color',[0.2,0.2,0.2],...
    'LineWidth',.5,'LineStyle',lStyles{1,6},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Threshold value Fr_0');

annotation(figure1,'textbox',...
    [0.721 .0433333333  0.8 0.1],... % [x_begin y_begin length height]
    'String',{'0.5'},...
    'FontName','Arial','FontSize',fontS,...
    'Color',[0.35,0.35,0.35],...
    'FitBoxToText','on',...%'BackgroundColor',[1 1 1],...
    'LineStyle','none');


fMakeXgrid(0.2:0.2:0.8,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:0.8,0.5);
    
% Create xlabel
xlabel('Upstream Froude number Fr_0 [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
% ylabel('Discharge coefficient \mu [-]',...
%     'FontSize',fontS,...
%     'FontName','Arial');  
annotation(figure1,'textbox',...
        [0.585 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...
        'LineStyle','none');

% set(legend,'Position',[0.6 0.75 0.2 0.2],'FontSize',fontS,...
%     'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1]);

% create water surface indicator
% annotation(figure1,'arrow',[0.202 0.201985],...
%     [0.8824 0.882],'HeadWidth',22,'HeadLength',13,'HeadStyle','plain');



if write2disc
    cd('figures');
    export_fig mu_hx_Fr.png -png
    export_fig mu_hx_Fr.eps -eps
    cd ..
    disp('Figure (mu_hx_Fr) written to disc (figures folder).');
    close all;
end

