function[] = fPlot_hx_Fr(Xhx,Xbhx,xInterphx,Yhx,Ybhx,yInterphx, ...
                lyInterphx, lyInterpFr, uyInterphx, uyInterpFr, ... 
                XFr,XbFr,xInterpFr,YFr,YbFr,yInterpFr, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 18;
MarkerS = 8;
xPos = 0.178; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
limColor = [.65 .65 .65];
colors=zeros(size(colors));
colors(7,:)=[0 0 0];
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
lStyles = {'none','none','none','-','-.'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3)/3.7 scrsz(4)]);



%% SUBPLOT a) -- hx
subplot1 = subplot(2,1,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:0.2:1,...
    'LineWidth', 1.5);
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 1]);
ylim(subplot1,[0. 1]);


% create plot of h* without bedload
plot1(1) = plot(Xhx(:,3),Yhx(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName','vertical a_*');
% create plot of b* without bedload
plot1(2) = plot(Xhx(:,2),Yhx(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName','lateral b_*');
% create plot of a*b* without bedload
plot1(3) = plot(Xhx(:,1),Yhx(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','combined a_*\cdot b_*');
lgnd = legend(subplot1,'show','Location','SouthWest');
%legend boxoff
%set(lgnd,'color','none');

% create plot of h* with bedload
plot1(4) = plot(Xbhx(:,3),Ybhx(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','top a_* (with bedload)');
% create plot of b* without bedload
plot1(5) = plot(Xbhx(:,2),Ybhx(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','lateral b_* (with bedload)');
% create plot of a*b* without bedload
plot1(6) = plot(Xbhx(:,1),Ybhx(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','combined a_* \cdot b_* (with bedload)');

% create plot of regression curve a*
plot1(7) = plot(xInterphx(:,3),yInterphx(:,3),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve b*
plot1(8) = plot(xInterphx(:,2),yInterphx(:,2),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve a*b*
plot1(9) = plot(xInterphx(:,1),yInterphx(:,1),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

% lower limits -----
% create plot of  regression curve a*
plot1(10) = plot(xInterphx(:,3),lyInterphx(:,3),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve b*
plot1(11) = plot(xInterphx(:,2),lyInterphx(:,2),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve a*b*
plot1(12) = plot(xInterphx(:,1),lyInterphx(:,1),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

% upper limits -----
% create plot of  regression curve a*
plot1(13) = plot(xInterphx(:,3),uyInterphx(:,3),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve b*
plot1(14) = plot(xInterphx(:,2),uyInterphx(:,2),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve a*b*
plot1(15) = plot(xInterphx(:,1),uyInterphx(:,1),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

fMakeXgrid(0.2:0.2:0.8,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:0.8,0.5);
% Create xlabel
xlabel('Constriction ratio [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Backwater ratio h_* [-]',...
    'FontSize',fontS,...
    'FontName','Arial');
annotation(figure1,'textbox',...
        [xPos 0.815  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...
        'LineStyle','none');

%% SUBPLOT b) -- Fr
subplot2 = subplot(2,1,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:0.2:1,...
    'LineWidth', 1.5);
hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0. 1]);
ylim(subplot2,[0. 1]);

% create plot of Fr without bedload
plot2(1) = plot(XFr(:,3),YFr(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName','top a_*');
% create plot of b* without bedload
plot2(2) = plot(XFr(:,2),YFr(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName','lateral b_*');
% create plot of a*b* without bedload
plot2(3) = plot(XFr(:,1),YFr(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','combined a_* \cdot b_*');
% legend(axes1,'show','Location','NorthWest');

% create plot of Fr with bedload
plot2(4) = plot(XbFr(:,3),YbFr(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','top a_* (with bedload)');
% create plot of b* without bedload
plot2(5) = plot(XbFr(:,2),YbFr(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','lateral b_* (with bedload)');
% create plot of a*b* without bedload
plot2(6) = plot(XbFr(:,1),YbFr(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','combined a_* \cdot b_* (with bedload)');

% create plot of regression curve a*
plot2(7) = plot(xInterpFr(:,3),yInterpFr(:,3),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve b*
plot2(8) = plot(xInterpFr(:,2),yInterpFr(:,2),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve a*b*
plot2(9) = plot(xInterpFr(:,1),yInterpFr(:,1),...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

% lower limits -----
% create plot of  regression curve a*
plot2(10) = plot(xInterphx(:,3),lyInterpFr(:,3),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve b*
plot2(11) = plot(xInterphx(:,2),lyInterpFr(:,2),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve a*b*
plot2(12) = plot(xInterphx(:,1),lyInterpFr(:,1),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

% upper limits -----
% create plot of  regression curve a*
plot2(13) = plot(xInterphx(:,3),uyInterpFr(:,3),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve b*
plot2(14) = plot(xInterphx(:,2),uyInterpFr(:,2),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% create plot of regression curve a*b*
plot2(15) = plot(xInterphx(:,1),uyInterpFr(:,1),...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

fMakeXgrid(0.2:0.2:08,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:08,0.5);

% Create xlabel
xlabel('Constriction ratio [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Upstream Froude number Fr_0 [-]',...
    'FontSize',fontS,...
    'FontName','Arial');  
annotation(figure1,'textbox',...
        [xPos 0.34  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...
        'LineStyle','none');

% set(legend,'Position',[0.6 0.75 0.2 0.2],'FontSize',fontS,...
%     'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1]);

% create water surface indicator
% annotation(figure1,'arrow',[0.202 0.201985],...
%     [0.8824 0.882],'HeadWidth',22,'HeadLength',13,'HeadStyle','plain');



if write2disc
    cd('figures');
    export_fig hx_Fr.png -png
    export_fig hx_Fr.eps -eps
    cd ..
    disp('Figure (hx_Fr) written to disc (figures folder).');
    close all;
end

