function[] = fPlotEtahxFr(Xhx,Xbhx,xInterphx,Yhx,Ybhx,yInterphx, ...
                lyInterphx, lyInterpFr, uyInterphx, uyInterpFr, ... 
                XFr,XbFr,xInterpFr,YFr,YbFr,yInterpFr, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
fontS = 46;
MarkerS = 24;
xPos = 0.15;%0.78; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
colors=zeros(size(colors));
colors(7,:)=[0 0 0];
limColor = [.65 .65 .65];
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
lStyles = {'none','none','none','-','-.'};
scrsz(3) = 1500;
figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(3) scrsz(3) scrsz(3)]);


%% PLOT Fr
axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:0.2:1,...
    'LineWidth', 1.5);
hold(axes1,'all');
box(axes1,'on');
grid(axes1,'off');

xlim(axes1,[0. 1]);
ylim(axes1,[0. 1]);

% create plot of Fr without bedload
plot1(1) = plot(XFr(:,3),YFr(:,3),'Parent',axes1,...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','vertical a_*');
% create plot of b* without bedload
plot1(2) = plot(XFr(:,2),YFr(:,2),'Parent',axes1,...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','lateral b_*');
% create plot of a*b* without bedload
plot1(3) = plot(XFr(:,1),YFr(:,1),'Parent',axes1,...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','combined a_* \cdot b_*');
% legend(axes1,'show','Location','NorthWest');
lgnd = legend(axes1,'show','Location','NorthWest');
% legend boxoff
% set(lgnd,'color','none');

% create plot of Fr with bedload
plot1(4) = plot(XbFr(:,3),YbFr(:,3),'Parent',axes1,...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','top a_* (with bedload)');
% create plot of b* without bedload
plot1(5) = plot(XbFr(:,2),YbFr(:,2),'Parent',axes1,...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','lateral b_* (with bedload)');
% create plot of a*b* without bedload
plot1(6) = plot(XbFr(:,1),YbFr(:,1),'Parent',axes1,...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','combined a_* \cdot b_* (with bedload)');

% create plot of regression curve Fr
plot1(7) = plot(xInterpFr,yInterpFr,'Parent',axes1,...
    'Color',[0.,0.,0.],...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% lower bounds
plot1(8) = plot(xInterpFr,lyInterpFr,'Parent',axes1,...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
% upper bounds
plot1(9) = plot(xInterpFr,uyInterpFr,'Parent',axes1,...
    'Color',limColor,...
    'LineWidth',1,'LineStyle',lStyles{1,5},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

fMakeXgrid(0.2:0.2:0.8,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:0.8,0.5);

% Create xlabel
xlabel('Upstream Froude number Fr_0 [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Ratio of bed shear stress \eta [-]',...
    'FontSize',fontS,...
    'FontName','Arial');  
% annotation(figure1,'textbox',...
%         [xPos 0.35  0.4 0.1],... % [x_begin y_begin length height] %y  =0.05 lower pos.
%         'String',{'b)'},...
%         'FontName','Arial','FontSize',fontS+2,...
%         'FontWeight','bold',...
%         'FitBoxToText','on',...
%         'BackgroundColor',[1 1 1],...
%         'LineStyle','none');

% set(legend,'Position',[0.6 0.75 0.2 0.2],'FontSize',fontS,...
%     'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1]);

% create water surface indicator
% annotation(figure1,'arrow',[0.202 0.201985],...
%     [0.8824 0.882],'HeadWidth',22,'HeadLength',13,'HeadStyle','plain');



if write2disc
    cd('figures');
    export_fig eta_hx_Fr.png -png
    export_fig eta_hx_Fr.eps -eps
    cd ..
    disp('Figure (eta_hx_Fr) written to disc (figures folder).');
    close all;
end

