function[] = fPlotMuHxOnly(X,Xb,xInterp, Y,Yb,yInterp, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
fontS = 32;
MarkerS = 16;
yPos = 0.20; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
colors=zeros(size(colors));

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'none','o','x','none'};
lStyles = {'-','none','none','-','-'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3)/1.5 scrsz(4)]);

axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.2:0.2:1,...
    'YTickLabel',{'','0.4','0.6','0.8','1.0'},...
    'YTick',0.2:0.2:1);
hold(axes1,'all');
box(axes1,'on');
grid(axes1,'on');

xlim(axes1,[0.2 1]);
ylim(axes1,[0.2 1]);

% create plot of Y without bedload
plot1(1) = plot(X(:,3),Y(:,3),'Parent',axes1,...
    'Color',colors(4,:),...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName','without bedload');
% create plot of Yb with bedload
plot1(2) = plot(Xb(:,3),Yb(:,3),'Parent',axes1,...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS+1,...
    'DisplayName','with bedload');
legend(axes1,'show','Location','NorthWest');
% create plot of regression curve
plot1(3) = plot(xInterp(:,3),yInterp(:,3),'Parent',axes1,...
    'Color',[0.55,0.55,0.55],...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');

% annotation(figure1,'textbox',...
%     [0.1334 yPos  0.4 0.1],... % [x_begin y_begin length height]
%     'String',{'a) top'},...
%     'FontName','Arial','FontSize',fontS,...
%     'FitBoxToText','on',...
%     'BackgroundColor',[1 1 1]);
% 'Color',[0.1 0.1 0.1]);
% 'FaceAlpha',0.4,...

% Create xlabel
xlabel('H_* [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Loss coefficient \mu [-]',...
    'FontSize',fontS,...
    'FontName','Arial');



% create plot of Y without bedload
plot1(4) = plot(X(:,2),Y(:,2),'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'Color',colors(4,:),...
    'DisplayName','without bedload');
% create plot of Yb with bedload
plot1(5) = plot(Xb(:,2),Yb(:,2),'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS+1,...
    'Color',colors(7,:),...
    'DisplayName','with bedload');
% create plot of regression curve
plot1(6) = plot(xInterp(:,2),yInterp(:,2),'Parent',axes1,...
    'Color',[0.55,0.55,0.55],...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
    

% create plot of Y without bedload
plot1(7) = plot(X(:,1),Y(:,1),'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'Color',colors(4,:),...
    'DisplayName','without bedload');
% create plot of Yb with bedload
plot1(8) = plot(Xb(:,1),Yb(:,1),'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS+1,...
    'Color',colors(7,:),...
    'DisplayName','with bedload');
% create plot of regression curve
plot1(9) = plot(xInterp(:,1),yInterp(:,1),'Parent',axes1,...
    'Color',[0.55,0.55,0.55],...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','Regression curve');
    





if write2disc
    cd('figures');
    export_fig muHxOnly.png -png
    export_fig muHxOnly.eps -eps
    cd ..
    disp('Figure(mu) written to disc (figures folder).');
    close all;
end

