function[] = fPlotEtaHxOnly(Xb,xInterp,Yb,yInterp,write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
fontS = 32;
MarkerS = 16;
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
colors=zeros(size(colors));

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','x','v','none'};
lStyles = {'none','none','none','-','-'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3)/1.5 scrsz(4)]);


axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:0.2:1);
hold(axes1,'all');
box(axes1,'on');
grid(axes1,'on');

xlim(axes1,[0. 1]);
ylim(axes1,[0. 1]);
%% PLOT TOP
plot1(1) = plot(Xb(:,3),Yb(:,3),'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'Color',colors(4,:),...
    'DisplayName','Top a_*');
%% PLOT LATERAL
plot1(2) = plot(Xb(:,2),Yb(:,2),'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS+1,...
    'Color',colors(7,:),...
    'DisplayName','Lateral b_*');
%% PLOT COMBINED
plot1(3) = plot(Xb(:,1),Yb(:,1),'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'Color',colors(9,:),...
    'DisplayName','Combined a_* and b_*');

legend(axes1,'show','Location','NorthWest');
%% PLOT INTERPOLATIONS
plot1(4) = plot(xInterp,yInterp,'Parent',axes1,...
    'LineWidth',1,'LineStyle',lStyles{1,4},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'Color',[0.55 0.55 0.55],...
    'DisplayName','Regression curve');

% annotation(figure1,'textbox',...
%     [0.1334 yPos  0.4 0.1],... % [x_begin y_begin length height]
%     'String',{'a) top'},...
%     'FontName','Arial','FontSize',fontS,...
%     'FitBoxToText','on',...
%     'BackgroundColor',[1 1 1]);
% 'Color',[0.1 0.1 0.1]);
% 'FaceAlpha',0.4,...

% Create xlabel
xlabel('Backwater ratio H_*  [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Shear stress reduction \eta [-]',...
    'FontSize',fontS,...
    'FontName','Arial');


% set(legend,'Position',[0.6 0.75 0.2 0.2],'FontSize',fontS,...
%     'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1]);

% create water surface indicator
% annotation(figure1,'arrow',[0.202 0.201985],...
%     [0.8824 0.882],'HeadWidth',22,'HeadLength',13,'HeadStyle','plain');



if write2disc
    cd('figures');
    export_fig etaHxOnly.png -png
    export_fig etaHxOnly.eps -eps
    cd ..
    disp('Figure(eta) written to disc (figures folder).');
    close all;
end

