function[] = fPlotHx(X,Xb,xInterp,xInterpb, Y,Yb,yInterp, yInterpb, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
fontS = 16;
MarkerS = 7;
xPos = 0.15; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
colors=zeros(size(colors));

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','x','v','none'};
lStyles = {'none','none','none','-'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3)/3.3 scrsz(4)*4]);

    %% SUBPLOT WITHOUT Qb
    subplot1 = subplot(2,1,1, 'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.:0.2:1);
    hold(subplot1,'all');
    box(subplot1,'on');
    grid(subplot1,'on');

    xlim(subplot1,[0 1]);
    ylim(subplot1,[0 1]);

    % create plot of a* without bedload
    plot1(1) = plot(X(:,3),Y(:,3),...
        'Color',colors(4,:),...
        'LineWidth',1,'LineStyle',lStyles{1,3},...
        'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
        'DisplayName','top a_* - H_*');
    % create plot of b* without bedload
    plot1(2) = plot(X(:,2),Y(:,2),...
        'Color',colors(7,:),...
        'LineWidth',1,'LineStyle',lStyles{1,2},...
        'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
        'DisplayName','lateral b_* - H_*');
    % create plot of a*b* without bedload
    plot1(3) = plot(X(:,1),Y(:,1),...
        'Color',colors(7,:),...
        'LineWidth',1,'LineStyle',lStyles{1,1},...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'DisplayName','combined a_* b_* - H_*^2');
    legend(subplot1,'show','Location','SouthEast');
    
    % create plot of regression curve a*
    plot1(4) = plot(xInterp(:,3),yInterp(:,3),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,4},...
        'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    % create plot of regression curve b*
    plot1(5) = plot(xInterp(:,2),yInterp(:,2),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,4},...
        'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    % create plot of regression curve a*b*
    plot1(6) = plot(xInterp(:,1),yInterp(:,1),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,4},...
        'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    
    annotation(figure1,'textbox',...
        [xPos 0.817  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS,...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...
        'LineStyle','none');
        % 'Color',[0.1 0.1 0.1]);
        % 'FaceAlpha',0.4,...

    % Create xlabel
    xlabel('Constriction ratio [-]','FontSize',fontS,'FontName','Arial');
    % Create ylabel
    ylabel('Backwater ratio [-]',...
        'FontSize',fontS,...
        'FontName','Arial');


%% SUBPLOT WITH Qb
    subplot2 = subplot(2,1,2, 'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.:0.2:1);
    hold(subplot2,'all');
    box(subplot2,'on');
    grid(subplot2,'on');

    xlim(subplot2,[0 1]);
    ylim(subplot2,[0 1]);

    % create plot of a* with bedload
    plot2(1) = plot(Xb(:,3),Yb(:,3),...
        'Color',colors(4,:),...
        'LineWidth',1,'LineStyle',lStyles{1,3},...
        'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
        'DisplayName','top a_* - H_*');
    % create plot of b* with bedload
    plot2(2) = plot(Xb(:,2),Yb(:,2),...
        'Color',colors(7,:),...
        'LineWidth',1,'LineStyle',lStyles{1,2},...
        'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
        'DisplayName','lateral b_* - H_*');
    % create plot of a*b* with bedload
    plot2(3) = plot(Xb(:,1),Yb(:,1),...
        'Color',colors(7,:),...
        'LineWidth',1,'LineStyle',lStyles{1,1},...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'DisplayName','combined a_* b_* - H_*^2');
    legend(subplot2,'show','Location','SouthEast');
    % create plot of regression curve a*
    plot2(4) = plot(xInterpb(:,3),yInterpb(:,3),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,4},...
        'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    % create plot of regression curve b*
    plot2(5) = plot(xInterpb(:,2),yInterpb(:,2),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,4},...
        'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    % create plot of regression curve a*b*
    plot2(6) = plot(xInterpb(:,1),yInterpb(:,1),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,4},...
        'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    
    annotation(figure1,'textbox',...
        [xPos 0.3425  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS,...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...
        'LineStyle','none');
        % 'Color',[0.1 0.1 0.1]);
        % 'FaceAlpha',0.4,...

    % Create xlabel
    xlabel('Constriction ratio [-]','FontSize',fontS,'FontName','Arial');
    % Create ylabel
    ylabel('Backwater ratio [-]',...
        'FontSize',fontS,...
        'FontName','Arial');
    
% set(legend,'Position',[0.6 0.75 0.2 0.2],'FontSize',fontS,...
%     'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1]);

% create water surface indicator
% annotation(figure1,'arrow',[0.202 0.201985],...
%     [0.8824 0.882],'HeadWidth',22,'HeadLength',13,'HeadStyle','plain');



if write2disc
    cd('figures');
    export_fig Hx.png -png
    export_fig Hx.eps -eps
    cd ..
    disp('Figure (Hx) written to disc (figures folder).');
    close all;
end

