function[] = fPlotZetaHx(X,Xb,xInterp, Y,Yb,yInterp, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
fontS = 24;
MarkerS = 9;
yPos = 0.20; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
colors=zeros(size(colors));

%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'none','o','x','none'};
lStyles = {'-','none','none','-','-'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/2.4]);

    %% SUBPLOT TOP
    subplot1 = subplot(1,3,1, 'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.2:0.2:1,...
    'YTickLabel',{'','0.5','1.0','1.5','2.0'},...
    'YTick',0:0.5:2);
    hold(subplot1,'all');
    box(subplot1,'on');
    grid(subplot1,'on');

    xlim(subplot1,[0.2 1]);
    ylim(subplot1,[0. 2]);

    % create plot of Y without bedload
    plot1(1) = plot(X(:,3),Y(:,3),...
        'Color',colors(4,:),...
        'LineWidth',1,'LineStyle',lStyles{1,2},...
        'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
        'DisplayName','without bedload');
    % create plot of Yb with bedload
    plot1(2) = plot(Xb(:,3),Yb(:,3),...
        'Color',colors(7,:),...
        'LineWidth',1,'LineStyle',lStyles{1,3},...
        'Marker',mStyles{1,3},'MarkerSize',MarkerS+1,...
        'DisplayName','with bedload');
    legend(subplot1,'show','Location','NorthWest');
    % create plot of regression curve
    plot1(3) = plot(xInterp(:,3),yInterp(:,3),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,1},...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    
    annotation(figure1,'textbox',...
        [0.1334 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a) top'},...
        'FontName','Arial','FontSize',fontS,...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1]);
        % 'Color',[0.1 0.1 0.1]);
        % 'FaceAlpha',0.4,...

    % Create xlabel
    xlabel('a_*/H_* [-]','FontSize',fontS,'FontName','Arial');
    % Create ylabel
    ylabel('Loss coefficient \zeta_{a,b} [-]',...
        'FontSize',fontS,...
        'FontName','Arial');


%% SUBPLOT LATERAL
    subplot2 = subplot(1,3,2, 'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.2:0.2:1,...
    'YTickLabel',{'','0.5','1.0','1.5','2.0'},...
    'YTick',0:0.5:2);
    hold(subplot2,'all');
    box(subplot2,'on');
    grid(subplot2,'on');

    xlim(subplot2,[0.2 1]);
    ylim(subplot2,[0. 2]);

    % create plot of Y without bedload
    plot2(1) = plot(X(:,2),Y(:,2),...
        'LineWidth',1,'LineStyle',lStyles{1,2},...
        'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
        'Color',colors(4,:),...
        'DisplayName','without bedload');
    % create plot of Yb with bedload
    plot2(2) = plot(Xb(:,2),Yb(:,2),...
        'LineWidth',1,'LineStyle',lStyles{1,3},...
        'Marker',mStyles{1,3},'MarkerSize',MarkerS+1,...
        'Color',colors(7,:),...
        'DisplayName','with bedload');
    % create plot of regression curve
    plot2(3) = plot(xInterp(:,2),yInterp(:,2),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,1},...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    
    % Create xlabel
    xlabel('b_*/H_* [-]','FontSize',fontS,'FontName','Arial');
    annotation(figure1,'textbox',...
        [0.4136 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b) lateral'},...
        'FontName','Arial','FontSize',fontS,...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1]);
    % Create ylabel
%     ylabel('Loss coefficient \zeta_{a,b} [-]',...
%         'FontSize',fontS,...
%         'FontName','Arial');

%% SUBPLOT COMBINED
    subplot3 = subplot(1,3,3, 'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.4','0.6','0.8','1.0','1.2'},...
    'XTick',0.4:0.2:1.2,...
    'YTickLabel',{'','0.5','1.0','1.5','2.0'},...
    'YTick',0:0.5:2);
    hold(subplot3,'all');
    box(subplot3,'on');
    grid(subplot3,'on');

    xlim(subplot3,[0.4 1.2]);
    ylim(subplot3,[0. 2]);

    % create plot of Y without bedload
    plot3(1) = plot(X(:,1),Y(:,1),...
        'LineWidth',1,'LineStyle',lStyles{1,2},...
        'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
        'Color',colors(4,:),...
        'DisplayName','without bedload');
    % create plot of Yb with bedload
    plot3(2) = plot(Xb(:,1),Yb(:,1),...
        'LineWidth',1,'LineStyle',lStyles{1,3},...
        'Marker',mStyles{1,3},'MarkerSize',MarkerS+1,...
        'Color',colors(7,:),...
        'DisplayName','with bedload');
    % create plot of regression curve
    plot3(3) = plot(xInterp(:,1),yInterp(:,1),...
        'Color',[0.55,0.55,0.55],...
        'LineWidth',1,'LineStyle',lStyles{1,1},...
        'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
        'DisplayName','Regression curve');
    
    % Create xlabel
    xlabel('a_*\cdot b_*/H_*^2 [-]','FontSize',fontS,'FontName','Arial');
    % Create ylabel
%     ylabel('Loss coefficient \zeta_{a,b} [-]',...
%         'FontSize',fontS,...
%         'FontName','Arial');
    
    annotation(figure1,'textbox',...
        [0.695 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'c) combined'},...
        'FontName','Arial','FontSize',fontS,...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1]);
 
% set(legend,'Position',[0.6 0.75 0.2 0.2],'FontSize',fontS,...
%     'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1]);

% create water surface indicator
% annotation(figure1,'arrow',[0.202 0.201985],...
%     [0.8824 0.882],'HeadWidth',22,'HeadLength',13,'HeadStyle','plain');



if write2disc
    cd('figures');
    export_fig zetaHx.png -png
    export_fig zetaHx.eps -eps
    cd ..
    disp('Figure (zeta) written to disc (figures folder).');
    close all;
end

